### ISSUE TITLE
Crash on startup when running as a service on Windows

### ISSUE THREAD

**Issue by blotus** [wasilibs/go-re2#144]
Hello,

After upgrading `go-re2` in [crowdsec](http://github.com/crowdsecurity/crowdsec) to the latest version, we saw a crash when running as a service in Windows (and only as a service, everything was fine when running the binary directly from the command line).

After some investigation, it turns out the issue was introduced in this [commit](0018040882d77d014edcfd5c6989737b4372ec27), more specifically this [line](https://github.com/wasilibs/go-re2/commit/0018040882d77d014edcfd5c6989737b4372ec27#diff-2f3e2205eb658dd44b63db621cd2a539a11a2b1a640bc440d221ff8d846f1863R98).

When windows starts a service, it looks like `stdout` and `stderr` are forcefully closed by the system, which makes them unusable (I cannot find any actual documentation about this, but according to my tests, they are).

`os.Stdout` and `os.Stderr` are passed to `InstantiateModule`, and because they are invalid, this call fails, which in turn makes `go-re2` panic.

 I have a minimal reproduction available in [this gist](https://gist.github.com/blotus/6a8e5c447ce57f719d9e99c3fd0ea700) (there's a bit of fluff to install/remove the service to make it easier to use).
 To reproduce:
  - Build the code above
  - Install the service (from an admin shell): `./repro.exe install`.
  - Attempt to start the service (from an admin shell): `Service-Start testService`
  - Observe the error returned by windows (if you have procmon running at the same time, you'll see the program exiting the status code `2`, which is [the code used by `panic`](https://github.com/golang/go/issues/24284))
  - Remove the service (from an admin shell): `./repro.exe remove`
  
  Unfortunately, it's quite hard to get any logs about this error (because the panic occurs in `init()`, so it will crash before my program can run any code), but patching `wazero` with various debug logging shows:
```
time="2024-09-12T00:48:03+02:00" level=info msg="InitFSContext(stdin=<nil>, stdout=*os.File, stderr=*os.File, fs=[], guestPaths=[], tcpListeners=[])"
time="2024-09-12T00:48:03+02:00" level=error msg="stdioWriterFileEntry(stdout, *os.File) failed: GetFileType /dev/stdout: The handle is invalid."
```

Which confirms `stdout` is indeed invalid.

I was not able to reproduce the issue on linux by running things like `./repro 1>&-`, but I guess it should be doable by setting `FD_CLOEXEC` on `stdout` before calling `execve` on a program that uses `go-re2`.
  
As a side note, have you ever thought about removing the use of `init()` (or at the very least, not calling `panic` in `init()` and somehow find a way to return the error to the user) ? I understand that it's needed for `go-re2` to be a drop-in replacement for `regexp`, but it makes it very hard (and confusing) to debug issues like this (it took me some time to realize that `go-re2` was calling `panic()`).

**Comment by anuraaga** [comment]
Hi @blotus - thanks for the report and sorry for the trouble, that's a gnarly issue. I think with regards to panic, we won't change the behavior since indeed being a drop-in replacement for `regexp`, presumably that was also important when introducing to crowdsec :) And module initialization is irrecoverable, making the whole go-re2 package unusable so it feels somewhat natural to me.

If there's some way to improve the panic message we could do that, I would figure the stack trace makes it relatively straightforward to find go-re2 is the cause though. Was there something specifically confusing about it that we could improve? Thanks

**Comment by blotus** [comment]
Thanks for the merge !

The hard part was getting the stacktrace (as stdout/stderr are closed, nothing can get outputted anywhere, and due to the way go resolves import order, go-re2 `init` was called before I could replace stderr with a valid handle or setup a `recover` call, and go-re2 was not my first suspect for the crash).

I've given some thoughts about this, and something that could probably be a good middle ground would be to replace the `panic` calls with something that sets an error flag inside go-re2, and check its value during the calls to `Compile`/`MustCompile`/.... or `Match`/`MatchString` and return an error/panic here.
This would technically change the behaviour compared to the standard `regexp` module, as this would be a new error type but it's probably acceptable (this is even something that could be hidden behind a build flag)

Admittedly, this is probably a niche issue (although I haven't spent the time trying to understand all the possible failure reasons during initialization), so maybe it's not actually worth spending the time of reworking this part, but if you are interested let me know, I'll open another issue to track this.

**Comment by anuraaga** [comment]
> go-re2 init was called before I could replace stderr with a valid handle

Ah, thanks for this example, indeed I can see why it was tricky. I like your idea a lot of propagating the error to read in the entry point functions rather than panicing during init, feel free to open an issue on it, I think we can make that change.
