### ISSUE TITLE
Unbounded memory growth when no match is found

### ISSUE THREAD

**Issue by thomas-thorburn-connect** [wasilibs/go-re2#56]
I found this library and was excited because I heard good things about google's regex library. The benchmarks I ran showed a significant improvement over the standard library, from 2x to 10x faster. But I found unbounded memory growth that should be investigated. 

I am using ubuntu 22.04 and it happens with wasm and cgo. 

```
github.com/wasilibs/go-re2 v1.3.0 
```
run this, you'll see constant memory usage
```
var a string

func main() {
	animalRegex := regexp.MustCompile(`dog`)
	for i := 0; i < 1000000000; i++ {
		a = animalRegex.ReplaceAllLiteralString(`The quick brown fox jumps over the lazy dog`, "animal")
	}

}
```

Modify it like so, so there are no matches and watch how your memory grows. I ran it with GOMAXPROCS=1

```
var a string

func main() {
	animalRegex := regexp.MustCompile(`cat`)
	for i := 0; i < 1000000000; i++ {
		a = animalRegex.ReplaceAllLiteralString(`The quick brown fox jumps over the lazy dog`, "animal")
	}

}

```

Notably, this behavior is not seen with the FindString,match or split variants

**Comment by anuraaga** [comment]
Thanks @thomas-thorburn-connect for this very detailed report! Was very easy to track down the issue thanks to it, fix in #57
