### ISSUE TITLE
random long time findstring

### ISSUE THREAD

**Issue by Nyx2022** [wasilibs/go-re2#60]
hello, i have almost 500 regex to findstring to 20000 various length text,as i test some times , i found this will occur a strange circumstance：
some time is a regex will cost a long time (servel s and more),and others are ms or us,but the next time will be b regex has this problem.in my tests,every time is a different regex to has this problem,so i think may it is not regex's problem, maybe this lib has some places need to improved or changed

**Comment by anuraaga** [comment]
Hi @Nyx2022 - would you be able to provide a code reproduction of the issue? There could be a problem but without a reproduction don't have a way to really investigate it. Thanks.

**Comment by anuraaga** [comment]
Hi @Nyx2022 - didn't get a response so am going to close this issue. Please feel free to reopen if you are able to help reproduce the problem. Thanks for the understanding.
