### ISSUE TITLE
Runtime cgo crash when building with -race flag and running FindAllSubmatchIndex

### ISSUE THREAD

**Issue by himelbrand** [wasilibs/go-re2#63]
First of all thanks for the amazing work you did here, this is a great improvement in performance 💪 
The issue that I found is the following:
It looks like there is some kind of issue with using cgo while using data race detector of go.
The output that I got is the following:
```
fatal error: checkptr: pointer arithmetic result points to invalid allocation

goroutine 242 [running]:
runtime.throw({0x205ba86?, 0x1e06a80?})
	/usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0xc000f5f770 sp=0xc000f5f740 pc=0x44e470
runtime.checkptrArithmetic(0xc000f5f848?, {0x0, 0x0, 0x0?})
	/usr/local/go/src/runtime/checkptr.go:69 +0xac fp=0xc000f5f7a0 sp=0xc000f5f770 pc=0x41b11c
github.com/wasilibs/go-re2/internal.matchFrom(...)
	/root/go/pkg/mod/github.com/wasilibs/go-re2@v1.4.0/internal/re2_tinygowasm.go:73
github.com/wasilibs/go-re2/internal.(*Regexp).findAllSubmatch(0xc00072bd10, {0x556f70?, 0x10001f8f8?}, 0xffffffffffffffff, 0xc000f5f970)
	/root/go/pkg/mod/github.com/wasilibs/go-re2@v1.4.0/internal/re2.go:485 +0x124 fp=0xc000f5f8d0 sp=0xc000f5f7a0 pc=0x15828e4
github.com/wasilibs/go-re2/internal.(*Regexp).FindAllSubmatchIndex(0xc00072bd10, {0xc0009e5400, 0x4e8, 0x500}, 0xc0009a8990?)
	/root/go/pkg/mod/github.com/wasilibs/go-re2@v1.4.0/internal/re2.go:415 +0x10c fp=0xc000f5f9d0 sp=0xc000f5f8d0 pc=0x1581a8c
```
then every other process on this pod started crashing as well...

this only happen when I run `go build` using both `-tags re2_cgo` and `-race`

Expected behaviour is the same as with out the race build flag, meaning running properly without crashing.

Please let me know if any other information is needed to investigate this issue, I will also do some investigating when I have the time, but wanted to let you know.

Thanks!

**Comment by anuraaga** [comment]
Thanks a lot for the report @himelbrand! This repo should have been running tests with `-race` all along and unfortunately missed it. I have created a PR to fix the issues with race detector, while enabling it in CI. Some of them did look like potential crashes in real-world so really good to have this in.

**Comment by himelbrand** [comment]
@anuraaga thanks a lot for the quick reply!
when will a new tag be released? so I could use the fixed version in my project?

**Comment by anuraaga** [comment]
@himelbrand I'd like to release one soon but currently am having trouble with the race detector on the Windows build

https://github.com/wasilibs/go-re2/blob/main/.github/workflows/ci.yaml#L71

I need some more time (and remembering to spend it when at a Windows machine...) to see if this is only a flake or indicative of an issue of some sort. Sorry for the delay

**Comment by ShayShwartz** [comment]
Hi @anuraaga,
I'm experiencing the same issue.

Do you have an update with an estimation for a fix?
Thanks!

**Comment by anuraaga** [comment]
Sorry for the huge delay - I still haven't been able to get machine time to investigate the windows issue but I think it's fine to release as it should still be better even if there may be a remaining issue on that OS. Thanks for the patience.

**Comment by ShayShwartz** [comment]
Thank you! appreciate it!
