### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by Richtermeister** [wasilibs/go-re2#68]
Hi there,

When trying to drop-in-place replace our stdlib regexp usage, it seems that case sensitivity behaves differently, and the setting to toggle this during compilation is buried in the internal package. Is there a way to access the setting?

Thank you for your help.

**Comment by anuraaga** [comment]
Hi @Richtermeister - can you provide an example of a regex that behaves differently with the stdlib? We run all their tests but if there's something missing it would be great to know.

As far as I know, both are supposed to behave as case sensitive, unless the `(?i)` flag is passed to make it insensitive (supporting the advanced expression API of golang is out of scope for this library).

https://pkg.go.dev/regexp

links to

https://github.com/google/re2/wiki/Syntax

Does that work for you?

**Comment by Richtermeister** [comment]
Hi @anuraaga and thank you for the quick reply. Alas, I'm unable to.. there must have been something wrong with my test setup, because now I'm unable to reproduce it. I'll keep an eye out, but for now this is a false alert. Sorry about that.
