### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by kris-dev-hub** [wasilibs/go-re2#69]
hello,

When I switched my project from the standard library to go-re2 memory consumption increased a few times.

This is memory usage on standard library after 30min
 701.69MB 95.28% 95.28%   701.69MB 95.28%  bufio.(*Scanner).Text (inline)
   10.09MB  1.37% 96.65%    16.59MB  2.25%  websitedata/internal/controllers.(*App).LoadHostData
    6.50MB  0.88% 97.54%     6.50MB  0.88%  go.mongodb.org/mongo-driver/bson/bsonrw.(*valueReader).readString
    4.51MB  0.61% 98.15%     4.51MB  0.61%  regexp/syntax.(*compiler).inst (inline)

This is memory usage on go-re2 after 5 minutes

 2678.14MB 83.98% 83.98%  2678.14MB 83.98%  github.com/tetratelabs/wazero/internal/wasm.(*MemoryInstance).Grow
  169.09MB  5.30% 89.28%   169.09MB  5.30%  github.com/tetratelabs/wazero/internal/wasm.NewMemoryInstance (inline)
  104.70MB  3.28% 92.56%   104.70MB  3.28%  github.com/tetratelabs/wazero/internal/engine/compiler.(*engine).NewModuleEngine
   94.54MB  2.96% 95.53%    94.54MB  2.96%  bufio.(*Scanner).Text (inline)
   85.33MB  2.68% 98.20%    85.33MB  2.68%  github.com/tetratelabs/wazero/internal/engine/compiler.(*moduleEngine).newCallEngine
    3.01MB 0.094% 98.30%    90.54MB  2.84%  websitedata/internal/controllers.(*App).ParseWatByLine
       3MB 0.094% 98.39%   342.04MB 10.73%  github.com/wasilibs/go-re2/internal.newABI

**Comment by anuraaga** [comment]
Hi @kris-dev-hub - as documented in the performance section of the README, indeed go-re2 uses much more memory than the standard library. I am working on a big change to the code that should mostly remove this overhead and will let you know when it's in.

**Comment by anuraaga** [comment]
@kris-dev-hub I just merged a change that redoes the execution model completely. As such, it will need some baking before releasing but would you be able to try the latest unreleased version `github.com/wasilibs/go-re2@0018040` and see if things look different for you? Real world data will be very helpful. Thank you.

**Comment by kris-dev-hub** [comment]
No more memory issues. Thank you very much for responding so quickly.

 102.21MB 90.60% 90.60%   102.21MB 90.60%  bufio.(*Scanner).Text (inline)
    3.01MB  2.67% 93.27%   100.21MB 88.83%  websitedata/internal/controllers.(*App).ParseWatByLine
    2.50MB  2.22% 95.48%     2.50MB  2.22%  reflect.mapassign0
    2.05MB  1.81% 97.30%     7.05MB  6.25%  websitedata/pkg/watimport.InitImport
    1.50MB  1.33% 98.63%     2.02MB  1.79%  github.com/wasilibs/go-re2/internal.Compile

**Comment by anuraaga** [comment]
Thanks for verifying @kris-dev-hub - I have released a prerelease of the next version with this improvement.
